import sys

class customexception(Exception):
    def __init__(self,error_message,error_details):
        pass
    
    def __str__(self):
        pass
    
        